baseURL = "https://cesdanses.rboud.ml/"
languageCode = "en-us"
title = "CesDanses"
summaryLength = 20
paginate = 5

[params]
favicon = "images/favicon.png"
herotitle = "CesDanses"
herolink = "#"
herolinktext = "don't click yet"

[hero]

[menu]
    [[menu.nav]]
        name    = "ateliers"
        pre = "<i class='fas fa-place-of-worship'></i>"
        url     = "ateliers"
        weight  = -1
    [[menu.nav]]
        name    = "Conférences"
        pre = "<i class='fas fa-list'></i>"
        url     = "conferences"
        weight  = -2
    [[menu.nav]]
        name    = "Master Classes"
        pre = "<i class='fas fa-envelope'></i>"
        url     = "master-classes"
        weight  = -3
    [[menu.nav]]
        name    = "L'équipe"
        pre = "<i class='fas fa-users'></i>"
        url     = "about"
        weight  = -4